[build]
  command = "CI=false npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_FIREBASE_AUTH_DOMAIN = "quantumfly.hatemsoliman.dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[context.production]
  environment = { NODE_ENV = "production" }